spring.application.name=movie-ticket-booking
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/movie_ticket_booking_system
spring.datasource.username=root
spring.datasource.password=9324070450
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.thymeleaf.cache=false
spring.mvc.hiddenmethod.filter.enabled=true
