package com.movieticket.controller;
import com.movieticket.entity.*; import com.movieticket.repository.*; import com.movieticket.service.BookingService; import jakarta.servlet.http.HttpSession; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.web.bind.annotation.*; import java.time.LocalDate; import java.util.*;
@Controller public class HomeController {
 private final MovieRepository movies; private final ShowRepository shows; private final SeatRepository seats; private final BookingService bookingService; private final BookingRepository bookings; private final PaymentRepository payments; private final UserRepository users;
 public HomeController(MovieRepository m,ShowRepository s,SeatRepository se,BookingService bs,BookingRepository b,PaymentRepository p,UserRepository u){movies=m;shows=s;seats=se;bookingService=bs;bookings=b;payments=p;users=u;}
 @GetMapping("/") public String home(@RequestParam(required=false) String q,Model model){model.addAttribute("movies",q==null||q.isBlank()?movies.findAll():movies.findByTitleContainingIgnoreCase(q));model.addAttribute("q",q);return "home";}
 @GetMapping("/register") public String register(Model m){m.addAttribute("user",new User());return "register";}
 @PostMapping("/register") public String registerPost(@ModelAttribute User u,Model m){if(users.findByEmail(u.getEmail()).isPresent()){m.addAttribute("error","Email already registered.");return "register";}u.setRole(Role.USER);users.save(u);return "redirect:/login?registered";}
 @GetMapping("/login") public String login(){return "login";}
 @PostMapping("/login") public String loginPost(@RequestParam String email,@RequestParam String password,HttpSession session,Model m){Optional<User> u=users.findByEmail(email);if(u.isEmpty()||!u.get().getPassword().equals(password)){m.addAttribute("error","Invalid email or password.");return "login";}session.setAttribute("user",u.get());return u.get().getRole()==Role.ADMIN?"redirect:/admin":"redirect:/";}
 @GetMapping("/logout") public String logout(HttpSession s){s.invalidate();return "redirect:/";}
 @GetMapping("/movie/{id}") public String movie(@PathVariable Long id,Model m){Movie movie=movies.findById(id).orElseThrow();m.addAttribute("movie",movie);m.addAttribute("shows",shows.findByMovieMovieIdAndShowDateGreaterThanEqualOrderByShowDateAscShowTimeAsc(id,LocalDate.now()));return "movie";}
 @GetMapping("/show/{id}/seats") public String seatPage(@PathVariable Long id,Model m){Show sh=shows.findById(id).orElseThrow();m.addAttribute("show",sh);m.addAttribute("seats",seats.findByScreenScreenIdOrderBySeatNumber(sh.getScreen().getScreenId()));m.addAttribute("booked",bookingService.bookedSeats(id));return "seats";}
 @PostMapping("/book") public String book(@RequestParam Long showId,@RequestParam List<Long> seatIds,@RequestParam(defaultValue="UPI") String paymentMethod,HttpSession session,Model m){User u=(User)session.getAttribute("user");if(u==null)return "redirect:/login";try{Booking b=bookingService.create(u.getUserId(),showId,seatIds,paymentMethod);return "redirect:/booking/"+b.getBookingId();}catch(Exception e){m.addAttribute("error",e.getMessage());Show sh=shows.findById(showId).orElseThrow();m.addAttribute("show",sh);m.addAttribute("seats",seats.findByScreenScreenIdOrderBySeatNumber(sh.getScreen().getScreenId()));m.addAttribute("booked",bookingService.bookedSeats(showId));return "seats";}}
 @GetMapping("/booking/{id}") public String booking(@PathVariable Long id,Model m,HttpSession s){Booking b=bookings.findById(id).orElseThrow();User u=(User)s.getAttribute("user");if(u==null||!b.getUser().getUserId().equals(u.getUserId()))return "redirect:/login";m.addAttribute("booking",b);m.addAttribute("items",List.of());payments.findByBookingBookingId(id).ifPresent(p->m.addAttribute("payment",p));return "booking";}
 @GetMapping("/my-bookings") public String myBookings(Model m,HttpSession s){User u=(User)s.getAttribute("user");if(u==null)return "redirect:/login";m.addAttribute("bookings",bookings.findByUserUserIdOrderByBookingDateDesc(u.getUserId()));return "my-bookings";}
 @PostMapping("/booking/{id}/cancel") public String cancel(@PathVariable Long id,HttpSession s){User u=(User)s.getAttribute("user");if(u!=null)bookingService.cancel(id,u.getUserId());return "redirect:/my-bookings";}
}
